[package]
name = "z33-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
z33-emulator = { path = "../emulator" }
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
rustyline = "7.0.0"
rustyline-derive = "0.4.0"
clap = "3.0.0-beta.2"
shell-words = "1.0.0"
ansi_term = "0.12.1"
