on:
  push:
  pull_request:
  release:
    types:
      - published

name: Compile

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04
            exe: z33-cli
            use-cross: true
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            exe: z33-cli
            use-cross: false
          - target: aarch64-apple-darwin
            os: macos-latest
            exe: z33-cli
            use-cross: false
          - target: x86_64-apple-darwin
            os: macos-12
            exe: z33-cli
            use-cross: false
          - target: x86_64-pc-windows-msvc
            os: windows-2022
            exe: z33-cli.exe
            use-cross: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Setup Rust build cache
        uses: Swatinem/rust-cache@v2

      - name: Build the binary
        uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target=${{ matrix.target }} -p z33-cli
          use-cross: ${{ matrix.use-cross }}

      - name: Upload the binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: z33-cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ matrix.exe }}

  publish:
    name: Upload the release artifacts
    needs: [build]
    runs-on: ubuntu-22.04
    if: github.event_name == 'release'

    steps:
      - name: Download the artifacts from the previous job
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Fix permissions (x86_64-apple-darwin)
        run: chmod +x artifacts/z33-cli-x86_64-apple-darwin/z33-cli

      - name: Fix permissions (aarch64-apple-darwin)
        run: chmod +x artifacts/z33-cli-aarch64-apple-darwin/z33-cli

      - name: Fix permissions (x86_64-unknown-linux-musl)
        run: chmod +x artifacts/z33-cli-x86_64-unknown-linux-musl/z33-cli

      - name: Fix permissions (aarch64-unknown-linux-musl)
        run: chmod +x artifacts/z33-cli-aarch64-unknown-linux-musl/z33-cli

      - name: Create darwin x86_64 archive
        run: tar -czvf z33-cli-x86_64-apple-darwin.tar.gz --owner=0 --group=0  -C artifacts/z33-cli-x86_64-apple-darwin/ z33-cli

      - name: Create darwin aarch64 archive
        run: tar -czvf z33-cli-aarch64-apple-darwin.tar.gz --owner=0 --group=0  -C artifacts/z33-cli-aarch64-apple-darwin/ z33-cli

      - name: Create linux x86_64 archive
        run: tar -czvf z33-cli-x86_64-unknown-linux-musl.tar.gz --owner=0 --group=0  -C artifacts/z33-cli-x86_64-unknown-linux-musl/ z33-cli

      - name: Create linux aarch64 archive
        run: tar -czvf z33-cli-aarch64-unknown-linux-musl.tar.gz --owner=0 --group=0  -C artifacts/z33-cli-aarch64-unknown-linux-musl/ z33-cli

      - name: Upload darwin x86_64 archive
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./z33-cli-x86_64-apple-darwin.tar.gz
          asset_name: z33-cli-x86_64-apple-darwin.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload darwin aarch64 archive
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./z33-cli-aarch64-apple-darwin.tar.gz
          asset_name: z33-cli-aarch64-apple-darwin.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload linux x86_64 archive
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./z33-cli-x86_64-unknown-linux-musl.tar.gz
          asset_name: z33-cli-x86_64-unknown-linux-musl.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload linux aarch64 archive
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./z33-cli-aarch64-unknown-linux-musl.tar.gz
          asset_name: z33-cli-aarch64-unknown-linux-musl.tar.gz
          asset_content_type: application/tar+gzip

      - name: Upload windows executable
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/z33-cli-x86_64-pc-windows-msvc/z33-cli.exe
          asset_name: z33-cli-x86_64-pc-windows-msvc.exe
          asset_content_type: application/vnd.microsoft.portable-executable
